### ISSUE TITLE
Sometimes the UI doesn't go hide

### ISSUE THREAD

**Issue by LorenzGit** [mesmotronic/air-fullscreen-ane#11]
On Nexus 7 2nd edition with Lollipop.
When the app starts the UI hides just fine although if I press and hold the power button, the UI reappear and sometimes when clicking very fast on the screen doesn't go away.

**Comment by wastedabuser** [comment]
Not sure if it is relevant to your problem, but i call immersiveMode on the native app activate event. I have bumped to cases when pressing the home button to go to the homescreen and then going back to the app shows the UI bars and they remain visible until the immersiveMode is called again.

**Comment by LorenzGit** [comment]
Yea that's what I do too and it works in any other case, although for some strange reason when you hold the power button, the menu that appears does not trigger deactivate/activate every time. Not sure if it is a bug in Air, Android or the ANE  itself.

**Comment by wastedabuser** [comment]
I just tested it, yes indeed the UI bars appear and stay.
I doubt it is and AIR bug as it seems the app does not get deactivated at all when the power off prompt appears. It continues to run in foreground.
I have encountered the same sticky UI bars on other apps (i guess non AIR). As far as i remember when the screen is touched they disappear. Not sure this is forcefully done by the developers encountering the same "bug"... It may be quick fix for you though if you don't feel like debugging the ANE.
If i get some free time the upcoming week i will look in it.

**Comment by LorenzGit** [comment]
I was thinking that too although wouldn't that mean calling immersiveMode every time the user clicks or at least having to check if the UI is up on every touch, unless maybe there is a way to detect the user pressed the power button.

**Comment by neilrackett** [comment]
The ANE will try to maintain the current full screen mode using the system events listed on the Android developer website, but I would also recommend calling `AndroidFullScreen.immersiveMode();` (or whichever mode you're using) again in your `Event.ACTIVATE` handler to ensure the correct mode is maintained, which should resolve 90% of the issues you're seeing. We're currently looking into the best way to better integrate this functionality into the ANE directly.

We haven't currently been able to identify a specific cause for the intermittent power menu issue because it doesn't necessarily affect all devices or OS versions. One theory is that it's caused by changes made to Android by handset manufacturers, but if anyone has a better idea, please let us know!

**Comment by LorenzGit** [comment]
Yes, definitely I am calling again every time Event.ACTIVE is dispatched, although the problem is that holding the power button does not Deactivate/Activate the view, it's almost like nothing ever happened, we have noticed the same issue with Facebook Friends Request overlay not dispatching Activate/Deactivate, we have fixed that one easily by calling immersiveMode again as soon as the user closes the overlay, but with the power button no event at all is ever dispatched.

We have tried this on Note 4, Nexus 7 and Nexus 9 with Lollipop, they all seem to behave identically.

**Comment by neilrackett** [comment]
We've found a likely solution to this issue, overriding the Android `Activity`'s `onWindowFocusChanged` to reset the UI visibility, but haven't yet found a way to implement this in an ANE context; you would normally override this in your app's own `Activity` class... which AIR apps don't have access to.

**Comment by LorenzGit** [comment]
In my opinion onWindowsFocusChanged should always dispatch an activate/deactivate on the NativeApplication, maybe it's a bug in Air that can be reported and hopefully fixed?

**Comment by neilrackett** [comment]
Please vote for https://bugbase.adobe.com/index.cfm?event=bug&id=3976714

**Comment by neilrackett** [comment]
This issue has now been resolved; see https://github.com/mesmotronic/air-fullscreen-ane/releases/tag/v1.3.0
