### ISSUE TITLE
Android system back button is overridden by immersvieMode

### ISSUE THREAD

**Issue by LorenzGit** [mesmotronic/air-fullscreen-ane#13]
The following code overrides the Android System Back Button, making it unusable with version 1.3.1 on Lollipop.

if(AndroidFullScreen.isSupported && AndroidFullScreen.isImmersiveModeSupported) {
	stage.displayState = StageDisplayState.NORMAL;
	AndroidFullScreen.showUnderSystemUI();
	AndroidFullScreen.immersiveMode();
}

**Comment by neilrackett** [comment]
Do you experience the same issue I find out don't use showUnderSytemUI first?

**Comment by LorenzGit** [comment]
For some unexplainable reason the issue happens even if I simply write:
if(AndroidFullScreen.isSupported && AndroidFullScreen.isImmersiveModeSupported) {}
