### ISSUE TITLE
Crashes during load on LG Optimus E970

### ISSUE THREAD

**Issue by mparrett** [mesmotronic/air-fullscreen-ane#14]
Thanks for the great extension. I'm testing it on a handful of devices right now and my first test device is having trouble. Maybe I'm doing something wrong here, but my app crashes when the extension is included (no actionscript code except `import com.mesmotronic.ane.AndroidFullScreen;`

Here's what I'm using in application.xml:

`<extensionID>com.mesmotronic.ane.fullscreen</extensionID>`
 
Here's an excerpt from the device log:

http://vpaste.net/VyQva

I'm not sure if this would matter, but I noticed my main project is using `-swf-version=25` and the extension is a version 28 swf. Odd since we're using AIR17. I'll try changing that and report back.

**Comment by mparrett** [comment]
Seems like that was the problem after all. Sorry for the noise!

**Comment by neilrackett** [comment]
No problem, glad you got it sorted.
