### ISSUE TITLE
fullScreen set to false in manifest causes issues with system bars showing

### ISSUE THREAD

**Issue by stevefawkner** [mesmotronic/air-fullscreen-ane#15]
This may not be an bug, but I thought I'd bring it up in case it can be solved.

I had cropping in my app, which was related to Issue #7 

Setting it to:

<fullScreen>false</fullScreen>

in the Android manifest solved the problem.

However in doing this, it caused other minor problems to appear, that didn't happen when fullScreen was set to true. I have several other ANEs hooked into the app (Google Play Games, Facebook etc.) and when fullScreen is set to false, while those extensions show the status/menu bars show too.

This is happening on two different Android devices (HTC One and Nexus 7) I've tested on, both running Android 5.0.2

I've tried a number of things to try and fix this, but have had no luck so far. Any idea on whether this can be fixed, or is it a limitation of the operating system or Adobe AIR?

**Comment by neilrackett** [comment]
This sounds similar to issue #11, where the bars appeared when the system power menu was displayed on some devices.

Unfortunately, this appears to be a combined limitation of AIR (which miscalculates the screen height when `fullScreen` is `true`) and the OS (we have no control when the app isn't focussed).

Right now, the ANE _should_ automatically reset the screen when the app next receives focus; if not, you'll need to manually reset the screen when your other ANEs close.
