### ISSUE TITLE
Black stripe in place of the UI bar on Galaxy S3 Neo when calling immersiveMode()

### ISSUE THREAD

**Issue by wastedabuser** [mesmotronic/air-fullscreen-ane#16]
When calling immersiveMode the UI hides but a black stripe remains. After the home button is pressed and then the multitask button to go back to application the black stripe disappears and and everything is fine!
This happens only on Samsung devices with Android 4.4.2 - 4.4.4 as far as i know...
On Nexus 4 and Nexus 7 both running Android 5 there isn't any problem!

There was NOT such problem with the initial release (prior to 1.3). Everything in my manifest is set correctly ... fullscreen is false. Yesterday i have updated to the latest release and the problem emerged.

My as3 code:
```
if (AndroidFullScreen.immersiveMode()) {
						stage.displayState = StageDisplayState.NORMAL;
						scW = AndroidFullScreen.immersiveWidth;
						scH = AndroidFullScreen.immersiveHeight;
						NativeApplication.nativeApplication.addEventListener(AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN, onFocusIn);
					} else {
						stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
						scW = stage.fullScreenWidth;
						scH = stage.fullScreenHeight;
					}
```

So i tried everything in as3, for example showUnderSystemUI() has the same issue.
The problem should be somewhere on the java side.

I still not very familiar with the Android immersive mode API, but i suspect the problem is somewhere in the resetUi method on the FullScreenContext class:
```
public void resetUi()
	{
		final View decorView = getDecorView();
		final Window window = getWindow();
		
		decorView.setOnFocusChangeListener(getOnFocusChangeListener());
		decorView.setOnSystemUiVisibilityChangeListener(null);
		
		window.clearFlags
		(
			WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION 
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS
		);
		
		init(); 
		
		setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);
	}
```
I suspect the window.clearFlags call  ... not sure yet.

I will update as soon as i find more!
Anyone else with a Samsung device to reproduce the problem?

**Comment by neilrackett** [comment]
The problem is in your AS3 code: you need to change the displayState to normal before calling immersiveMode().

**Comment by wastedabuser** [comment]
When i said i tried everything in as3 i also thought about it. I tried this code also:
```
if (AndroidFullScreen.isImmersiveModeSupported) {
						stage.displayState = StageDisplayState.NORMAL;
						scW = AndroidFullScreen.immersiveWidth;
						scH = AndroidFullScreen.immersiveHeight;
						AndroidFullScreen.immersiveMode();
NativeApplication.nativeApplication.addEventListener(AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN, onFocusIn);
					} else {
						stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
						scW = stage.fullScreenWidth;
						scH = stage.fullScreenHeight;
					}
```

**Comment by neilrackett** [comment]
This issue has been discussed several times in previous issues and the easiest way to prevent it is to ensure that you set `<fullScreen>false</fullScreen>` in your `app.xml` and use:

```actionscript
if (!AndroidFullScreen.immersiveMode())
{
    stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
    // full screen code
}
else
{
    // immersive mode code
}
```

**Comment by wastedabuser** [comment]
Dude, the fullScreen is set to false in the xml (as i stated in my first post).
Your code does not work either... :(
I even tried adding a 5 second timeout after the stage.displayState is set and then call immersiveMode...

Reverted to this commit 0e18f9c7d60d4828d99b56330212545efff0b67e (the one before your 1.3.0 release) and it all works fine!

**Comment by neilrackett** [comment]
Can you watch the output from your app via DDMS using Eclipse or Android Studio and let me know if you see any errors?

**Comment by wastedabuser** [comment]
I have access to this device only at night :)
The first thing i checked is for errors ... well there aren't any

It seems my hypothesis is right. I have commented this block
```
window.clearFlags
		(
			WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION 
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS
		);
```
Now everything is working correctly, at least for me...
Excuse me for my ignorance, but why do you need it?

I am forking and pushing my setup here: https://github.com/wastedabuser/air-fullscreen-ane. I have also added a build.xml for quick command line ant build.

**Comment by neilrackett** [comment]
The `clearFlags` call is used to ensure the UI is reset correctly when switching between various modes, but if it's causing issues with Samsung devices, I'll revise/move it and add in your build script.

**Comment by wastedabuser** [comment]
Well i guess there should be a flag that bypasses the initial call of the ```resetUi```. I guess you don't need to call ```resetUI``` when calling immersiveMode for the first time (my tests confirm this also).

Something like:
```
	public void resetUi()
	{
		if (!allowResetUi){
			allowResetUi = true;
			return;
		}
				
		final View decorView = getDecorView();
		final Window window = getWindow();
		
		decorView.setOnFocusChangeListener(getOnFocusChangeListener());
		decorView.setOnSystemUiVisibilityChangeListener(null);
		
		window.clearFlags
		(
			WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_FULLSCREEN
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION 
			| WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS
		);
		
		init(); 
		
		setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);
	}
```

Anyway, thank you for your work!

Regards,

**Comment by neilrackett** [comment]
Removing `clearFlags` caused problems with `showSystemUI`, so I've moved the code around and it looks like it's working as expected on a couple of test devices here. I've also added in your ant script.

Can you give [release 1.3.3](https://github.com/mesmotronic/air-fullscreen-ane/releases/tag/v1.3.3) a try on your Neo and let me know if it resolves the issues?

**Comment by wastedabuser** [comment]
Yes, it works properly on all my devices now!
Thanks!

**Comment by neilrackett** [comment]
:-)
