### ISSUE TITLE
Cannot open the app

### ISSUE THREAD

**Issue by williamshum** [mesmotronic/air-fullscreen-ane#17]
Hi,

I have used air-fullscreen ane 1.2.x before, everything works fine but sometimes cannot hide the navigation bar automatically. It seems that the issue is fixed, so that I downloaded the latest version 1.3.3. However after I have packaged the apk and installed on my device, the app cannot start. Eclipse only showing that Process com.xxx.xxx has died.

Thanks,

William

**Comment by neilrackett** [comment]
1. Can you confirm that you're using AIR 17 or above? (See issue #14)
1. Does this issue only affect a specific device or OS version?
1. Is there any additional information about the cause of the crash in DDMS?

**Comment by williamshum** [comment]
Thanks for your reply, yes the problem is swf-version. I am using version 25 so that errors occurred. Now the app work great.
