### ISSUE TITLE
LG Nexus 4 immersiveMode() issue

### ISSUE THREAD

**Issue by neolit123** [mesmotronic/air-fullscreen-ane#20]
hello,

LG Nexus 4 (Android 5.1.1)

on load the test app flashes for a split second, then black screen and then the app shows. similar to a resolution swap or screen adjustment on the desktop. i can't seem to be able to hide the "flashing".

the set of calls are:
AndroidFullScreen.showUnderSystemUI();
AndroidFullScreen.immersiveMode();

any idea how to resolve this one?
thanks

**Comment by wastedabuser** [comment]
Hi,

Using the same device with the same Android version and AIR 17.
Not experiencing any flashing (my background is black at the time the code is called though).

My code is:
```
if (AndroidFullScreen.isSupported) {
	if (AndroidFullScreen.isImmersiveModeSupported) {
		stage.displayState = StageDisplayState.NORMAL;
		AndroidFullScreen.immersiveMode();
		scW = AndroidFullScreen.immersiveWidth;
		scH = AndroidFullScreen.immersiveHeight;
		NativeApplication.nativeApplication.addEventListener(AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN, onFocusIn);
	} else {
		stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
		scW = stage.fullScreenWidth;
		scH = stage.fullScreenHeight;
	}
} else {
	scW = stage.fullScreenWidth;
	scH = stage.fullScreenHeight;
}
```

Hope this helps!

Are you calling the two one after another?
Or just both calls are giving you the flickering?

**Comment by neolit123** [comment]
> Not experiencing any flashing (my background is black at the time the code is called though).

my test case is a Starling Image which is added to the stage *after* the two fullscreen calls are made. it seems as if the full screen mode is not immediate but delayed after the Starling Image is already visible. i may have to find a way how to wait (listen) for that to happen and only then add visible elements.

> Are you calling the two one after another?
yes.

> Or just both calls are giving you the flickering?
i need to try that.

**Comment by wastedabuser** [comment]
I don't think you are supposed to call them one after another. Why would you ever need to?
 If you need to take the entire screen and hide the UI call:
```
AndroidFullScreen.immersiveMode();
```
If you need to extend your app to full screen but still keep the UI call:
```
AndroidFullScreen.showUnderSystemUI();
```
Having both one after another makes no sense to me...

**Comment by neolit123** [comment]
ok, i was able to solve this one the following way: i put AndroidFullScreen.immersiveMode(); and a the AndroidFullScreen.ANDROID_WINDOW_FOCUS_IN listener in the document class (e.g. Main.as). also as you suggested showUnderSystemUI() is indeed redundant.

the reason for the flickering was that a stage resize handler is added and triggered *before* the immersiveMode() call, and somehow this causes it. now immersiveMode() is the first call in the whole app.

thanks for the hints.
