### ISSUE TITLE
Why do I have to set -swf-version=28 for the flex compiler for this ane to work?

### ISSUE THREAD

**Issue by flashguy22** [mesmotronic/air-fullscreen-ane#21]
I would like to use your ane in a flex mobile android application. Unfortunately it doesn't compile until I set the compiler argument: -swf-version=28. Why is this necessary and is there maybe a different way of getting it to compile? 

I'm asking because I use a peer2peer approach in this app, which breaks when setting this compiler argument. 
NetConnection.Connect.Success still fires then I set up a GroupSpecifier and NetGroup where NetGroup.Connect.Success also fires.

NetGroup.Neighbor.Connect is the event which isn't triggered anymore after setting the additional compiler argument so I would like to avoid setting it.

Thanks in advance for any help!

**Comment by neilrackett** [comment]
You only need `-swf-version` if you're using AIR SDK <17, in which case I would suggest updating your Flex SDK using the [Apache Flex SDK Installer](http://flex.apache.org).

**Comment by flashguy22** [comment]
Thanks for the fast reply but I'm using AIR SDK 18 and get this error when compiling: included native extension 'com.mesmotronic.ane.fullscreen' includes a SWF version 28 which is greater than the version of the root SWF of this application: 14
Using Flex 4.6 with AIR 18 overlayd.

**Comment by neilrackett** [comment]
It makes sense that you'd need `-swf-version=28` if you're using Flex 4.6, as that will compile to SWF 14, FP 11.1 by default. From the error, it looks like the compiler is still using SWF 14, so you could try adding `-target-player=18.0` too.

However, I'd suggest upgrading to Apache Flex 4.14.1 with AIR 18 instead; you won't need to make any changes to your code as all versions of Apache Flex are designed as replacements for 4.6.

**Comment by flashguy22** [comment]
Thanks for the tip. I now tried Apache Flex and it compiles without any additional arguments. Unfortunately the NetGroup Code isn't working. I just don't get the NetGroup.Neighbor.Connect Event triggered. But this has nothing to do with your ane. I will look into this separately. 
Thanks for your fast help and the great work on the ane!

**Comment by neilrackett** [comment]
Glad you're (almost) up and running. Good luck with the NetGroup issue and enjoy the ANE!

**Comment by flashguy22** [comment]
Ok, got it working now. Compiled my server app also with the Apache SDK and tada, the messaging is working. By forcing the sdk with the compiler flag I of course used a newer sdk than on my server app.

Thanks again!

**Comment by neilrackett** [comment]
:-)
