### ISSUE TITLE
Question about Compiling against an older SDK

### ISSUE THREAD

**Issue by Sonorpearl** [mesmotronic/air-fullscreen-ane#22]
With what Tools do I need to compile this ANE?
By the Way I am using Mac. 
And I already tried it with Eclipse ADT, Android Compiler and Flash Builder with the ADT Plugin.

If I change the Runtime in the extension.xml and tried to build it with adt this error occurs:

adt -package -target ane ./AndroidFullScreen.ane extension.xml -swc swc/fullscreen-ane-android.swc -platform Android-ARM -C android . -platform Android-x86 -C android . -platform default -C default .

Invalid swc file. The extension NameSpace requires the SWF verison to be 25 or lower.
(btw. verison (version) is spelled wrong)

I have done nothing before that. I didnt compile anything, especially not the Java Part, since no Programm finds and Project in there.

-- Why do I need to compile it? --

For my Apps I am using: "Apache Flex 4.13.0 - Air 14" and I need it since in newer Versions some Buttons and Styles got removed. And the workload to fix that, would be too huge. But may be done in the future.

So I want to compile the ANE against that, older Version.

I need to have the newest Source as .ANE since there is a Bug which just got fixed in the last 2 Versions, but those need a higher Runtime.

The System UI does not get hidden after the Programm has lost Focus once, that is the Issue I am facing, which got fixed.

With friendly Regards
Jan aka. Sonorpearl

**Comment by neilrackett** [comment]
The current release build is compiled against Apache Flex 4.14.1 SDK with AIR 17.

If you're using an older SDK, try editing the namespace at the top of `extension.xml` in the `build` folder, in your case replace `17.0` with `14.0`, or downloading 4.13 with AIR 17+ using the [installer](http://flex.apache.org/installer.html).

The misspelt error message comes from the SDK, so might be worth reporting [here](https://issues.apache.org/jira/browse/FLEX).

**Comment by IgorGanapolsky** [comment]
@neilrackett Where is **17.0 and 14.0** in extension.xml?

**Comment by neilrackett** [comment]
It's at the end of the first line and is currently set to `24.0`:

`<extension xmlns="http://ns.adobe.com/air/extension/24.0">`
